### ISSUE TITLE
v0.94.262 regression: load_previous_plan() crashes with TypeError, Plan.__init__() missing 'soc_penalty_cost' — solver completely down

### ISSUE THREAD

**Issue by purcell-lab** [code-imstillalive/nimbus#785]
**Severity: high — real, live, currently-reproducing outage on the household's own install.** Deployed v0.94.263 (which includes v0.94.262's #781 fix), restarted, and every solve cycle since has crashed. `sensor.nimbus_status` reads "Needs attention", `sensor.nimbus_solver_battery_forecast` and `sensor.nimbus_solver_lp_status` are both `unknown` (no data at all) — the solver is not producing any plan right now.

## The error, from the live error log (4 occurrences since restart, recurring every cycle)

```
2026-09-12 21:08:28.549 ERROR (SyncWorker_7) [custom_components.nimbus_load.solver_runtime] Nimbus Solver: solve cycle failed
Traceback (most recent call last):
  File "custom_components/nimbus_load/solver_runtime.py", line 597, in _run_one_cycle
    sw.main()
  File "custom_components/nimbus_load/solver_writer.py", line 11703, in main
    previous_plan = load_previous_plan()
  File "custom_components/nimbus_load/solver_writer.py", line 4322, in load_previous_plan
    return network.Plan(
        status="optimal",
        ...
    )
TypeError: Plan.__init__() missing 1 required positional argument: 'soc_penalty_cost'
```

## Root cause (from the v0.94.262 release notes)

#781's fix added a new `Plan.soc_penalty_cost` field to `network.Plan` (`network.py`) as a required positional argument, and updated the construction sites `build_plan()` itself uses. It did not update `solver_writer.py`'s own `load_previous_plan()`, which reconstructs a `Plan` object from the persisted previous-plan cache for proximal-regularization purposes (`previous_plan=` in `build_plan()`) — that construction site is still calling the old signature, so it now crashes on every single solve cycle, not just an edge case.

## Impact

Every solve cycle fails outright — no new plan, no updated forecast, `sensor.nimbus_status` down. This is a regression introduced by #781's own fix, worse in practice than the bug it fixed (a cosmetic-but-wrong cost breakdown vs. a fully non-functional solver).

## Suggested fix

Either give `load_previous_plan()`'s `Plan(...)` construction the new `soc_penalty_cost` field (presumably `0.0` or reconstructed from the persisted data if it's stored), or make the field optional with a safe default on `Plan.__init__()` if that's consistent with how the rest of the codebase treats it. Given how many call sites construct `Plan` directly (this is at least the second one missed — worth grepping for every `network.Plan(` / `Plan(` construction site project-wide to confirm no others are affected before calling this fixed).

**Comment by purcell-lab** [comment]
Highlights the importance of devhub testing, if devhub is unavailable, one needs to be very cautious with new releases.
